spring:
  docker:
    compose:
      enabled: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          
server:
  port: 8082

logging:
  level:
    org.apache.kafka: error
    io.github.springwolf: debug